### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by pblottiere**
I  replaced some `QPushButton` by `QAction` because the icon is bigger this way.

### CODE REVIEW

**Comment by pblottiere** [comment]
@Fred1511 Can you take a look please?

**Comment by Fred1511** [comment]
@pblottiere Very pretty ! 
I propose to add tooltips to the buttons because the meaning of each icon is not that obvious for a beginner

**Comment by Fred1511** [comment]
@pblottiere and on a second thought, may be there is more explicit images ?
The "session" btn and the "followers" btn are very clear. But the second and the fourth aren't.
May be a loupe for the "observation" btn ?
For the "effort" btn, may be a head with a drop of sweat ?

**Comment by pblottiere** [comment]
> May be a loupe for the "observation" btn ?

What do you think about -> ?

image

> For the "effort" btn, may be a head with a drop of sweat ?

Mmm I'm not sure. While the "effort" word is used by the client, I don't think it's really representing the content of the environment table. Typically, a "new effort means:

- observer has switched
- the weather has changed 

That's why I choose an icon with a cloud (the weather) and a silhouette (the observer).

**Comment by pblottiere** [comment]
@Fred1511 I added some tooltips and updated the observation icon.

**Comment by Fred1511** [comment]
@pblottiere It works fine !

**Pull request merged**
