### PR TITLE
T028 v2 add world map layer

### PR DESCRIPTION
**Pull request by Fred1511**

### CODE REVIEW

**Comment by pblottiere** [comment]
The layer is not found:

error

**Comment by pblottiere** [comment]
It's maybe due to my environment, I'm investigating.

**Comment by pblottiere** [comment]
Once properly installed, it works well, thanks :+1:.

However, the map is empty by default. Can you zoom on the world layer by default?

**Comment by Fred1511** [comment]
> Once properly installed, it works well, thanks +1.
> However, the map is empty by default. Can you zoom on the world layer by default?
Done

**Pull request merged**
