### PR TITLE
Avoid unexplained pushError

### PR DESCRIPTION
**Pull request by pblottiere**
https://github.com/hytechimaging/sammo-boat/pull/90

### CODE REVIEW

**Comment by pblottiere** [comment]
@SebastienPeillet

**Comment by SebastienPeillet** [comment]
I believe we should integrate 8cc7cb4a025c5eb1453d40643fc3334c8f7ce1f6 commit too. In the first place, I noticed the pushError on the effort layer, but it happens for all layers

**Comment by pblottiere** [comment]
> I believe we should integrate 8cc7cb4 commit too. In the first place, I noticed the pushError on the effort layer, but it happens for all layers

Done. Can you take a second look please?

**Comment by SebastienPeillet** [comment]
Good to me now ! :+1:

**Pull request merged**
