### PR TITLE
Better effort management

### PR DESCRIPTION
**Pull request by SebastienPeillet**
Convert GPS status dock in a button to enable/disable the GPS (also Shift+G shortcut). Stopping the gps also ends the current effort by adding and `End` status effort entity.

Futhermore a check has been added before validation to verify each `effortGroup` has a `Begin` entity and a `End` entity.

A new action has been to duplicate a row. User can define a new datetime (the point geometry will be interpolate between closest gps records). On environment table, the status and the effortGroup can be also defined to fix errors before validation

### CODE REVIEW

**Comment by pblottiere** [comment]
A warning message could be useful if I click on the new GPS button whereas there isn't any GPS device connected.

**Comment by pblottiere** [comment]
> Stopping the gps also ends the current effort by adding and End status effort entity.

I don't see the `End` ligne added in the form. First, I need to click on the `Update environment` button (in this case, a `End` line is created before the `Begin`)

**Comment by pblottiere** [comment]
It's not related to this PR but a click on the `Validate (all or current selection)` button also focus the `routeType` widget like in https://github.com/hytechimaging/sammo-boat/pull/174#issuecomment-1327486236.

**Comment by pblottiere** [comment]
Can you update the title of the window please?

image

**Comment by SebastienPeillet** [comment]
> I don't see the End line added in the form. First, I need to click on the Update environment button (in this case, a End line is created before the Begin)

Do you add a `Begin` effort, before that ? I didn't mention it in the ticket. It only add a `End` effort if there is a ongoing effort

**Comment by pblottiere** [comment]
>>    I don't see the End line added in the form. First, I need to click on the Update environment button (in this case, a End line is created before the Begin)

> Do you add a Begin effort, before that ? I didn't mention it in the ticket. It only add a End effort if there is a ongoing effort

Yes. And I think that the `End` is added, but the form is not refreshed.

**Comment by pblottiere** [comment]
> A new action has been to duplicate a row. User can define a new datetime (the point geometry will be interpolate between closest gps records). On environment table, the status and the effortGroup can be also defined to fix errors before validation

I tried to duplicate a row but the form is not refreshed and I don't see the new record. Moreover, can we keep only 3 digits for the point coordinate?

image

**Comment by SebastienPeillet** [comment]
> > > I don't see the End line added in the form. First, I need to click on the Update environment button (in this case, a End line is created before the Begin)
> 
> > Do you add a Begin effort, before that ? I didn't mention it in the ticket. It only add a End effort if there is a ongoing effort
> 
> Yes. And I think that the `End` is added, but the form is not refreshed.

ok, I don't have this behaviour but I add an explicit refresh, you can retest it

**Comment by pblottiere** [comment]
BTW, I noticed that sometime, I still have `datetime out of bonds` whereas it looks good to me:

image

ps: in the image above, the `17:17:30` is a `End`.

**Comment by pblottiere** [comment]
The form is correctly refreshed now (for the auto `End` record as well as for the duplicate action) :+1:

**Comment by pblottiere** [comment]
And what do you think about https://github.com/hytechimaging/sammo-boat/pull/173#issuecomment-1327618540?

**Comment by SebastienPeillet** [comment]
> A warning message could be useful if I click on the new GPS button whereas there isn't any GPS device connected.

It's added now, we prevent to enable GPS if it's not detected

**Comment by pblottiere** [comment]
> So i guess there was still no gps point after 17:17:28 when you tried to duplicate the entity

OK :+1:.

+1 to merge when you're ready then :)

**Pull request merged**
