### PR TITLE
Update sighting conf

### PR DESCRIPTION
**Pull request by pblottiere**
https://github.com/hytechimaging/sammo-boat/pull/86

### CODE REVIEW

**Comment by SebastienPeillet** [comment]
To be sure, are you allright with the `species` widget behavior ?  There is no completion but the constraint indicates the the user if the value is in the species table.

Maybe we should cherry-pick 7cd69f9b21a393302dc5e3430cdebe48d920c92e to this PR to add soft constraint

**Comment by pblottiere** [comment]
@SebastienPeillet this PR is not ready yet

**Comment by pblottiere** [comment]
@SebastienPeillet can you take a quick look please?

**Comment by SebastienPeillet** [comment]
@pblottiere Good to me, indeed it's clearer with `CASE WHEN THEN` syntax :+1:

**Pull request merged**
